language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
os:
  - linux
# command to install dependencies
install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a
    # Replace dep1 dep2 ... with your dependencies
    - conda create -q -n test-environment --show-channel-urls --channel conda-forge python=$TRAVIS_PYTHON_VERSION scipy scikit-learn
    - source activate test-environment
    - pip install coveralls
    - pip install codecov
# command to run tests
script: coverage run --branch --source=strflab -m unittest discover --start-directory=tests
after_success:
  - coveralls
  - codecov